services:
  redis:
    container_name: customer-portal-redis
    image: redis:7.2.5
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis:/data
    networks:
      - customer-portal-redisnet
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      disable: true
    command: ['redis-server', '--requirepass ${REDIS_PWD}']
    env_file:
      - .env

  redisinsight:
    container_name: customer-portal-redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '127.0.0.1:9991:8001'
    networks:
      - customer-portal-redisnet
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ['CMD', 'curl --fail http://127.0.0.1:8001/healtcheck || exit 1']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - redisinsight:/db

volumes:
  redis:
    driver: local
  redisinsight:

networks:
  customer-portal-redisnet:    